### ISSUE TITLE
PhoneNumberActivity is not cleared

### ISSUE THREAD

**Issue by njovy** [twitter/digits-android#10]
As PhoneNumberActivity is started with ACTIVITY_NEW_TASK flag, it leaves another application in recent apps. Is there any reason why this activity is called with the flag? I think this is confusing since users see two different windows from one app. Plus, the window is still there after callback.

![device-2015-06-30-225540](https://cloud.githubusercontent.com/assets/1792070/8432632/33572ea6-1f7c-11e5-8490-bf812035f91f.jpg)

**Comment by rallat** [comment]
The activity is open with this flag, otherwise the user will had to start the flow again from the beginning when leaving the app, since Digits activities are hidden from the history back.

**Comment by njovy** [comment]
Is it possible to clear this activity explicitly when the user finishes this authentication?

**Comment by efrohnhoefer** [comment]
This issue will be addressed in the next release. Currently, we were using the ACTIVITY_NEW_TASK because the Activity was being launched using a Application Context provided by Fabric. On API 14+ we will use the [ActivityLifecycleCallbacks](http://developer.android.com/reference/android/app/Application.ActivityLifecycleCallbacks.html) to determine the current Activity and use the associated context to launch Digits without the ACTIVITY_NEW_TASK flag.
