### ISSUE TITLE
Digits works fine for all device except Samsung, i this error message

### ISSUE THREAD

**Issue by orignMaster** [twitter/digits-android#26]
![img-20150918-wa0002](https://cloud.githubusercontent.com/assets/5031930/9967489/6131292c-5e32-11e5-9468-fb9f3d22c66a.jpg)

**Comment by JonathanBaby** [comment]
Hy orignMaster, I see a small airplane icon in the status bar. Is'nt the device in "airplane mode", preventing it from network access ?

**Comment by orignMaster** [comment]
i dont think its the airplane cos this is the third samsung device i tried on. as you can c the wireless is still on.

**Comment by dustedrob** [comment]
I don't think this issue is related to the model of the phone. I've encountered this problem across several phones with different numbers and carriers. The guys at Digits set up a support form for this kind of problems: https://docs.google.com/forms/d/1dDMpmgfOuCRvEHlXfnsylF4MIrDgIMm3dSrndGEhrFo/viewform

Hope this helps, If you come across a solution, i'd be interesting in knowing it, since it's causing a lot of problems for me too.

**Comment by nntr** [comment]
Hi,

Small comment. I realized that Digits start working(you may try with Cannonball app for android) for phone number after successful login with digits at http://cannonballapp.io/ 
I tried another phone number (without login at http://cannonballapp.io/) and I observe this error again.(but first phone number is working now)

**Comment by efrohnhoefer** [comment]
Possibly related to #44.

**Comment by efrohnhoefer** [comment]
Closing for now since there isn't much info on this thread. Likely related to #44.
